name: Actualizar métricas de lenguajes

on:
  schedule:
    - cron: '*/6 * * * *'
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generar métricas de lenguajes
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

      - name: Push cambios al README
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Actualizar métricas de lenguajes" || echo "No changes to commit"
          git push || echo "No changes to push"
